### ISSUE TITLE
Never hide behindview completely

### ISSUE THREAD

**Issue by ghost** [jfeinstein10/SlidingMenu#153] opened 2012-11-27 11:56 UTC
Hey! I'm just checking out some "slideNavi"-libraries and yours is until now the best (by far!), so thanks for your hard work and for your clean programming style!

What I'm trying to achieve is a slidingmenu that never gets hidden completely. Instead I want it to have a semi-opened state of something like 50dp (= the width of the icons of the menu-items) and a fully-opended state which shows the list items in their complete width (icon + text).

This way the user could always use the menu, since he is always able to click the list items. But he is also able to make some room on the display by pushing the slidingmenu to its semi-opened state.

How would you approach this enhancement? I'd suggest two new fields within CustomView Behind...something like

boolean isSemiClosed => default false
int semiClosedWidth => default 50dp, since this results in a ~9mm area that is good to touch for a normal finger

Do you agree? Is there the possibility that you could add this feature anytime soon?

Hope to hear from you!
br,
muetzenflo

**Comment by jfeinstein10** [comment] 2012-11-27 14:43
Seems to be a duplicate of #65. It's currently in development too :)

**Closed as completed by jfeinstein10** 2012-11-27 14:43 UTC

**Comment by ghost** [comment] 2012-11-27 14:44
damn, I thought I searched all issues for that, sorry for bothering you :) thx for the info!
