### ISSUE TITLE
Cannot interact with menu's view when enable TOUCHMODE_FULLSCREEN

### ISSUE THREAD

**Issue by purepure** [jfeinstein10/SlidingMenu#344] opened 2013-03-22 08:11 UTC
I setup the slidingmenu in my project and it works well until I set touchmode for behind view by 
slidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
slidingMenu.setTouchModeBehind(SlidingMenu.TOUCHMODE_FULLSCREEN);
When enable touch mode(TOUCHMODE_FULLSCREEN) for behind view, I cannot interact with the view. I place a list view and some buttons but cannot do any thing with them. It's like a transparent view over lay.

plz fix!

**Comment by meecha** [comment] 2013-03-22 08:48
Happen on me either, 
Samsung Galaxy Nexus

**Comment by svenfalk** [comment] 2013-03-22 09:13
Also experienced this problem on a Samsung Galaxy Nexus GT7501 with Android 3.2 (API Level 13).

**Comment by nickbw2003** [comment] 2013-03-22 09:19
seems like this is a bug on android 3.x tablets, because anything is working nice on our nexus 4 (android 4.2.2) and galaxy S I9000 (android 2.3.3)

**Comment by purepure** [comment] 2013-03-22 09:25
I used android 2.3.3 but this issue still occurred. not tested on 4.2.2.

**Comment by nickbw2003** [comment] 2013-03-22 10:23
further hint: if I set a action for touches on my controls in menu + content, they are doing their things but they don't refresh their views

**Comment by jwoolston** [comment] 2013-03-22 13:17
There is a known bug with setTouchModeBehind. This is nothing new.

**Comment by NaiveBz** [comment] 2013-03-22 13:36
it got problem with Nexus 4 (android 4.2.2) as well. the listview at leftMenu and righMenu is not clickable and scollable when "setTouchModeBehind to "TOUCHMODE_FULLSCREEN".

**Comment by svenfalk** [comment] 2013-03-22 15:36
@jwoolston: thanks for the response. But would you mind telling which issue that would be? All the issues I found were already closed.

Nevertheless we went back to the revision https://github.com/jfeinstein10/SlidingMenu/commit/fa64e7aa52f1be9d2e9e051396f90197f4da7639 and the problem seems not to exist there. So the issue arised anywhere between Jan 9th. and now. Maybe it is related to the hardware acceleration change jfeinstein10 commited these days. But that is only a wild guess.

Regards and thanks for the nice work till now!

**Comment by jwoolston** [comment] 2013-03-22 15:45
See issue #131. All other issues have been closed as duplicates of 131. He is working on a fix but for now has publicly stated (through a response to the other issues) that using touch mode behind is not recommended unless you want to deal with the bugs yourself. Your specific problem may be different or bring more insight to the bug, but the fact remains that there is a known issue regarding the use of that method. We too are waiting for it to be fixed but it is a low priority for us (would be nice, but not required) so we have not taken a detailed look at finding a solution ourselves.

**Comment by venator85** [comment] 2013-04-01 09:55
Any news for this issue? Thanks

**Comment by purepure** [comment] 2013-04-01 10:23
As I understand, this issue has very low priority, so the author will not fix for this time. You should not use this feature(or trying deal with that)

**Comment by calbertts** [comment] 2013-04-04 14:51
I have de same problem on Samasum Galaxy Tab. :(

**Comment by jfeinstein10** [comment] 2013-04-12 22:28
For now, FULLSCREEN mode won't work on the menu. It's on the To-do list though.

**Closed as completed by jfeinstein10** 2013-04-12 22:28 UTC

**Comment by aka-jiashu** [comment] 2013-06-07 06:11
Same problem, but I've seen apps that using sliding-menu and both AboveView & BehindView is working with FULLSCREEN mode~ Tried to deal with this, failed... Hope somebody can fix this~
Thx for your excellent job.

**Comment by singggum3b** [comment] 2013-11-15 07:06
The problem's caused by improper touch event dispatch.(Which should be handled & dispatch in the Sliding Viewgroup instead of AboveView - the event never get to BehindView)

**Comment by dimitrireef** [comment] 2013-11-15 07:53
Use SlidingMenu.TOUCHMODE_MARGIN instead of full screen
