### ISSUE TITLE
Set side menu to always show partially

### ISSUE THREAD

**Issue by egfconnor** [jfeinstein10/SlidingMenu#258] opened 2013-01-24 18:00 UTC
Is it possible to enable the side menu to always show partially, so for example I can have some icons showing at all times for navigation? They would still be able to swipe the main content to expose some more info on the side menu, but on close it would not fully close and would still show the icons.

**Comment by jfeinstein10** [comment] 2013-01-28 15:20
Duplicate of #65 
This will be coming eventually

**Closed as completed by jfeinstein10** 2013-01-28 15:20 UTC
