### ISSUE TITLE
Samsung Galaxy s GT-i9000

### ISSUE THREAD

**Issue by Blucreation** [jfeinstein10/SlidingMenu#115] opened 2012-10-29 12:22 UTC
I have users with this phone who say that the slide menu doesn't not work for them. Can anyone confirm this so i know if its an issue with the slid menu or something else?

**Comment by McPo** [comment] 2012-10-29 12:37
using a jb rom. It's best to increase the width from 10 to 16. There's a
patch available in an issue which improves the hit width.

**Comment by Blucreation** [comment] 2012-10-29 13:11
I use full screen :confused:

**Comment by jfeinstein10** [comment] 2012-10-29 14:12
The default is actually 20 now. I was led to believe that this issue was fixed

**Comment by Blucreation** [comment] 2012-10-29 14:16
Dont take my word for it, it could be my code that's causing it but i don't have a galaxy s to run debug on

**Comment by Blucreation** [comment] 2012-10-29 22:48
My App: https://play.google.com/store/apps/details?id=com.fantasy.premier.unofficial

Can someone with a Galaxy S test? Slide menu is only enabled once or logged in, swiping anywhere should open menu, also app icon in action bar will toggle menu.

Seems mostly everyone posting negative reviews on my app have a Galaxy S :(

**Comment by redwarp** [comment] 2012-10-29 23:51
I confirm it. I have a Galaxy S, created an account for testing purposes and : nope, no sliding menu will pop. Actually, it appeared once and once only, but it was all glitchy, and half displayed only. But since this first time, nothing. I have a screen shot if you want

**Comment by jfeinstein10** [comment] 2012-10-30 02:32
I'll need some more info / a Galaxy S phone in order to work on a solution. Can't really debug it now because I don't have access to any of it. I'll bet it's something strange and phone dependent since it works well on every other device.

**Comment by dmalis** [comment] 2012-10-30 05:28
Some time ago, I was working on a project that was meant to run mostly on
galaxy ace phones. After wrapping it up, someone from agency i was
freelancing for called and explained to me, that we need to build a hack
in, because these phones have issues with buttons placed on the edge of the
screen. Actually, one couldn't click on a button that was too close to the
screen's edge.

So, maybe you are experiencing the same issue on your phone. Although
clicking on actionbar's home opens the menu as it should. If so, let me
know and I'll try to find that peace of code,that solved not working
buttons in the archives.

Damien

**Comment by redwarp** [comment] 2012-10-30 08:07
Well, just to be clear : the sliding menu demo app works perfectly fine on my Galaxy S. But it's not working with Blucreation's application.

**Comment by Blucreation** [comment] 2012-10-30 09:54
Yeah im thinking it could be an issue with the android version and my implementation. :cry: I'm struggling to find details so i can set up a galaxy s in AVD.

redwarp can you check something else for me? once your logged in to my app can you see if the user id and game week is filled in in menu->settings

**Comment by zengar** [comment] 2012-11-01 05:14
I actually had a problem with a Galaxy S as well. It kept breaking on dispatchWindowFocusChanged when called in the CustomViewAbove with a nullpointerexception (stacktrace below). This issue happened when I'd try and open a submenu (in the actionbar) or when clicking on list items in my behind view.

My hackish work around was to override the dispatchWindowFocusChanged and catch nullpointerexception in CustomViewAbove. But I'm not sure the base base root cause.

Phone was running 2.2. Model 9000T. I tested on a 2.2 emulator and 2.2 LG and didn't have the same problem.

```
11-01 15:36:41.154: E/AndroidRuntime(3364): FATAL EXCEPTION: main
11-01 15:36:41.154: E/AndroidRuntime(3364): java.lang.NullPointerException
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.widget.TabHost.dispatchWindowFocusChanged(TabHost.java:298)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:662)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:662)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:662)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:662)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:662)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:662)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:662)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1921)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.os.Handler.dispatchMessage(Handler.java:99)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.os.Looper.loop(Looper.java:123)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at android.app.ActivityThread.main(ActivityThread.java:4627)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at java.lang.reflect.Method.invokeNative(Native Method)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at java.lang.reflect.Method.invoke(Method.java:521)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-01 15:36:41.154: E/AndroidRuntime(3364):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jfeinstein10** [comment] 2013-01-28 15:32
Is this discussion still relevant? I'm going to close it because it's discussing code from 3 months ago.

**Closed as completed by jfeinstein10** 2013-01-28 15:32 UTC
