### ISSUE TITLE
Allow library to open from both left and right

### ISSUE THREAD

**Issue by endryha** [jfeinstein10/SlidingMenu#95] opened 2012-10-04 15:29 UTC
Is it possible to implement sliding not only from left but from right side too, so an application will have two side navigation panels at left and at right

**Comment by jfeinstein10** [comment] 2012-10-04 15:36
This is a duplicate of #20
Please look through other current issues before posting a new one :)
You can read all about the progress there

**Closed as completed by jfeinstein10** 2012-10-04 15:36 UTC

**Comment by endryha** [comment] 2012-10-04 16:11
sorry for duplicating things, I got through the current issues but didn't realized that #20 is the same thing

**Comment by icastell** [comment] 2012-10-04 16:38
@jfeinstein10 I think you mean #8 instead of #20 @endryha

**Comment by endryha** [comment] 2012-10-04 16:39
yes, you are correct

**Comment by jfeinstein10** [comment] 2012-10-04 16:40
^ What he said! I don't know where I got 20 from...
