### ISSUE TITLE
TouchMode MARGIN does not work on some devices

### ISSUE THREAD

**Issue by chrisjenx** [jfeinstein10/SlidingMenu#32] opened 2012-07-26 10:57 UTC
Hi,

Great work, as mentioned on twitter the MARGIN touch mode does not work on some devices.

Thus far found that this is an issue on Samsung Note, HTC Sensation (coincidently running Gingerbread 2.3.4).
(fyi, FULLSCREEN works on these devices, but of course that breaks the view pager).

I have a few more devices that I will get round to testing it on, If i solve the problem I shall pull request it.

Cheers,
Chris

**Comment by jfeinstein10** [comment] 2012-07-26 17:23
Thanks for filing this here. Hopefully, I'll have some debug instructions for you later so we can see what's going on completely. Off to work for now!

**Comment by chrisjenx** [comment] 2012-07-26 22:11
Yeah no worries I shall have a quick play tomorrow and see if I see whats going on, I am going to assume those devices are missing/firing different touch events.

But lemme know your thoughts and hopefully combined efforts can fix it!

**Comment by Tombarr** [comment] 2012-08-07 01:35
For what its worth I just tested this on my Samsung Galaxy S3. Smooth scrolling no longer works unless the menu is already open.

Also, multitouch causes an IllegalArgumentException on most of my devices (all running ICS). It seems the pointer index is out of range.

**Comment by chrisjenx** [comment] 2012-08-07 09:15
Ahh thats good to know @Tombarr It doesn't crash for me but using two fingers does mess up the swiping. Had a very quick look, seems that it's not grabbing the first 'pinky' just the general touch event, so I might see if I can change that so it grabs the first finger events.

Oh and by smooth scrolling you mean?

**Comment by Tombarr** [comment] 2012-08-07 11:51
@Chrisjenx Sorry, smooth scrolling was my reference to handling touch events. It seems on the Galaxy S3 that paging touch slop is 64 and the sliding threshold is 10. A drag event never occurs if the touch mode is MARGIN because of this, so unless the menu is already open I cannot swipe to open it.

The crashes happen very reliably for me. I use two or three fingers and removing the original seems to trigger it. I fixed it myself by replacing all getX() calls with my own that wraps that with a try-catch for IllegalArgumentException. If the exception is caught I use getX/getY without any arguments.

Finally, the other bug (maybe this is intentional) but the behind view NEVER receives touch events. This means its more of an image and can't be used functionally. This isn't a Galaxy S3 issue either, it happens on every device I've tested including older ones like the Droid X. I'll check Hierarchy Viewer later and see what comes up but it looks like the CustomViewAbove consumes all events always.

Tom

**Comment by jfeinstein10** [comment] 2012-08-07 14:39
Whoa. I've never seen the behind view not receive touch events. I've also been testing on devices 2.3 and up from different manufacturers and have never had that problem. I'd be interested in seeing what you find.

**Comment by Tombarr** [comment] 2012-08-07 14:53
@jfeinstein10 This happens reliably on ALL of my devices (RAZR, Galaxy S3, Galaxy Nexus, and Droid X all for Verizon). They are running 4.0.4, 4.0.4, 4.1.1, and 2.3.4 respectively. What I am doing is using the TOUCHMODE_MARGIN. I've tried both buttons and a ListView in my behind view (I'm setting them dynamically with setContentView and setContentViewBehind), no click events EVER go to ContentViewBehind. This happens even with TOUCHMODE_FULLSCREEN or setSlidingEnabled(false). ContentViewAbove seems to consume all events always.

Also, its probably bad practice but this is my modified code. I use the get*Safely methods instead of getX/getY as it prevents the issue with invalid pointers during multi-touch events. I also modified the onSecondaryPointerUp to use the last finger placed down, its not strictly necessary but it feels better during use in my opinion than always following the first finger.

Note: there is still a bug where if you use multiple fingers and not enough velocity is applied for a sling, the ContentViewAbove gets stuck half-way. At this point it only starts dragging from the original marginal area, not what is visible. I think there's an issue with the ACTION_UP that doesn't snap it back to the correct position.

```
           private void onSecondaryPointerUp(MotionEvent ev) {
        final int pointerIndex = MotionEventCompat.getActionIndex(ev);
        final int pointerId = MotionEventCompat.getPointerId(ev, pointerIndex);
        if (pointerId == mActivePointerId) {
            // This was our active pointer going up. Choose a new
            // active pointer and adjust accordingly.
            final int newPointerIndex = (pointerIndex == 0) ? (ev.getPointerCount() - 1) : 0;
            try {
                mLastMotionX = MotionEventCompat.getX(ev, newPointerIndex);
            } catch (IllegalArgumentException e) {
                mLastMotionX = ev.getX();
            }
            mActivePointerId = MotionEventCompat.getPointerId(ev, newPointerIndex);
            if (mVelocityTracker != null) {
                mVelocityTracker.clear();
            }
        }
    }

           public float getXSafely(MotionEvent ev) {
        float x = 0;
        try {
            final int activePointerIndex = MotionEventCompat.findPointerIndex(
                        ev, mActivePointerId);
            x = MotionEventCompat.getX(ev, activePointerIndex);
        } catch (IllegalArgumentException e) {
            x = ev.getX();
        }

        return x;
    }

    public float getYSafely(MotionEvent ev) {
        float y = 0;
        try {
            final int activePointerIndex = MotionEventCompat.findPointerIndex(
                        ev, mActivePointerId);
            y = MotionEventCompat.getY(ev, activePointerIndex);
        } catch (IllegalArgumentException e) {
            y = ev.getY();
        }

        return y;
    }
```

**Comment by chrisjenx** [comment] 2012-08-07 14:59
Thats odd, I think something else is at play here in your ContentView(). I have tested across a host off devices, MARGIN does not always work, but never crashes.

But the multi touch is an issue with the menu getting stuck, but never FC.

**Comment by Tombarr** [comment] 2012-08-07 15:15
@chrisjenx In its own Activity or with ViewPager my ContentView works just fine. I can assure you by setting ContentViewAbove.DEBUG to true, ALL touch events are consumed by it and NOT the ContentViewBehind (I've added log calls there too).

As for crashing, clearly I'm not the only one with this issue. Try three or four fingers all attempting to pull the menu. I'm not saying its practical to do this, but I can reproduce this consistently. Even with two fingers occasionally this happens. 
https://github.com/jfeinstein10/SlidingMenu/issues/27

**Comment by chrisjenx** [comment] 2012-08-07 15:33
@Tombarr Sorry I didn't mean to make it sound like I don't believe you, just I really can't reproduce the crash.

**Comment by Tombarr** [comment] 2012-08-07 15:45
@chrisjenx No worries, I'll try my Galaxy nexus later and get some logs but they all look like that issue. They point to IllegalArgumentException's with getX. I only know that my code is hackish but doesn't cause a force close when I use a couple of fingers and try to swipe with all of them.

**Comment by jfeinstein10** [comment] 2012-08-07 18:59
Two things:
1 - I tried to reproduce the crash you got using multiple fingers. For me, it never crashes or force closes, but it does have the behavior that is referred to in the other issue report (it stays semi-open). This is definitely a problem that I'll have to work on, but I can't seem to get it to crash on any device. If you could record a video of the crash and send a stack trace, then I'd be more than happy to look at it and try to fix it.
2 - I also can't seem to be able to reproduce the case where the behind view doesn't intercept touches. There was actually an issue report that I just closed 5 minutes ago where the behind view was intercepting touches that weren't meant for it (so too many touches). Again, if you could send a video or other info I'd be happy to try to help. 

Also, are you experiencing these issues with the example app or some project that you've built? If it's something that you've built, do you experience the same issues on the example app?

Thanks for your help and for reporting submitting your reports; I'd really like to try to resolve these issues the best that I can.

**Comment by Tombarr** [comment] 2012-08-07 19:18
So here is the log file. I removed all of my personal information (Samsung logs WAY too much) but the IllegalArgumentException and reference to ExampleActivity appear.

[log.txt](http://pastebin.com/PGiwsZ0b) on Pastebin.
Also a screenshot of the force-close message on [imgur](http://imgur.com/wC7yQ).

I'll try for Screencast but I'm almost positive it will not work on any of my devices (maybe the Droid X if I am lucky). That'll be a while for sure.

To reproduce this issue I pretty much took three fingers and scrolled around. It is more than I anticipate from any normal user, but since the app I am working on is a contract gig a known force-close will not fly. I'll be removing SlidingMenu later today, maybe when it's stable I can re-introduce it.
1. I'm not sure what good a video would do as "proof." If you can't reproduce the issue maybe its a localized incident but it definitely happens. In the ExampleActivity all is well so this is likely a bug on my end, I'll do my best to figure out what but probably an improper use of SlidingMenu.

**Comment by jfeinstein10** [comment] 2012-08-07 19:32
Try pulling the changes I just pushed and let me know what happens.

**Comment by jfeinstein10** [comment] 2012-08-07 20:04
I just fixed the multi finger touch bug (where it would stay open), so this may have been fixed in the process. Also I didn't want the video as "proof" just to see how exactly I could recreate it.

**Comment by Tombarr** [comment] 2012-08-07 21:33
@jfeinstein10 Well the good news is that on my Galaxy S3 I can confirm the multi-touch issue is cleared up (no more crashing). I also cannot get the sliding menu to stick halfway anymore (in the example project and my app).

I still do have the issue with touch events though in my app. I have the following code that might be relevant:

```
setSlidingActionBarEnabled(false); // Static ActionBar!
    setContentView(R.layout.user); // This is a ListView
    setBehindContentView(R.layout.frame); // Same as sample

    // Set the ContentViewBehind. SettingsFragment is another ListView.
final FragmentTransaction mTrans = getSupportFragmentManager().beginTransaction();
mTrans.replace(R.id.frame, new SettingsFragment());
mTrans.commit();

    // Get the sliding menu.
    getSlidingMenu().setBehindOffset((int) (getWindowWidth(this) / 5)); // This works just fine.
getSlidingMenu().setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN); // Workaround for the issue with touch events not scrolling on the Galaxy S3.
getSlidingMenu().setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);
getSlidingMenu().setOnOpenListener(this);
getSlidingMenu().setOnCloseListener(this);
```

Also, I thought I would try to contribute some code myself (I've made a number of changes to my own version of the library for testing so I don't want to merge anything). It doesn't fix any bugs but I thought it would be better to have the most accurate status bar height calculation. That resource works 99.9% of the time, but just in case it doesn't I added the XHDPI value for fallback.

```
    private static final int LOW_DPI_STATUS_BAR_HEIGHT = 19;
private static final int MEDIUM_DPI_STATUS_BAR_HEIGHT = 25;
private static final int HIGH_DPI_STATUS_BAR_HEIGHT = 38;
private static final int XHIGH_DPI_STATUS_BAR_HEIGHT = 50;

/**
 * Find the height of the current system status bar.
 * If this cannot be determined rely on a default.
 */
private static final int mHeightId = Resources.getSystem()
    .getIdentifier("status_bar_height", "dimen", "android");
private static final int mBarHeight;

// Try to retrieve the system's status bar height
// by querying the system's resources.
static {

    int mHeight = 0;

    if (mHeightId != 0) {
        try {
            mHeight = Resources.getSystem()
                .getDimensionPixelSize(mHeightId);
        }
        catch(Resources.NotFoundException e) { }
    }

    mBarHeight = mHeight;
};

public void setFitsSysWindows(boolean b) {
    if (Build.VERSION.SDK_INT >= 14) {
        super.setFitsSystemWindows(b);
    } else {
        int topMargin = 0;
        if (b) {
            topMargin = getStatusBarHeight();
        }
        RelativeLayout.LayoutParams params = ((RelativeLayout.LayoutParams)mViewBehind.getLayoutParams());
        int bottom = params.bottomMargin;
        int left = params.leftMargin;
        int right = params.rightMargin;
        params.setMargins(left, topMargin, right, bottom);
    }
}

private int getStatusBarHeight() {

    // Use our system resource?
    if (mBarHeight != 0) return mBarHeight;

    DisplayMetrics displayMetrics = new DisplayMetrics();
    ((WindowManager) getContext().getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay().getMetrics(displayMetrics);
    int statusBarHeight = 0;

    // Fall back on using System DisplayMetrics.
    switch (displayMetrics.densityDpi) {
    case DisplayMetrics.DENSITY_XHIGH:
        statusBarHeight = XHIGH_DPI_STATUS_BAR_HEIGHT;
        break;
    case DisplayMetrics.DENSITY_HIGH:
        statusBarHeight = HIGH_DPI_STATUS_BAR_HEIGHT;
        break;
    case DisplayMetrics.DENSITY_MEDIUM:
        statusBarHeight = MEDIUM_DPI_STATUS_BAR_HEIGHT;
        break;
    case DisplayMetrics.DENSITY_LOW:
        statusBarHeight = LOW_DPI_STATUS_BAR_HEIGHT;
        break;
    default:
        statusBarHeight = MEDIUM_DPI_STATUS_BAR_HEIGHT;
    }

    return statusBarHeight;
}
```

**Comment by jfeinstein10** [comment] 2012-08-07 22:18
WOO for the lack of crash! Also, thanks for the status bar fix. I didn't know that Android had a built in status_bar_height dimension; pretty cool.

Another question: 
When you say that the above view intercepts all the touches does that mean that it acts as though you've set TOUCHMODE_FULLSCREEN for the behind touch mode; as in you can always slide the menu? Or does it intercept them, route touches to onTouchEvent and then not do anything with them?

**Comment by chrisjenx** [comment] 2012-08-07 22:21
@Tombarr  when you say 

``` java
setContentView(R.layout.user); // This is a ListView
```

Im assuming your mean it is wrapped in a ViewGroup? Not just a list view by its self?

**Comment by Tombarr** [comment] 2012-08-07 22:27
@jfeinstein10 No crashes is exciting (although I'm really trying to keep this library in my contracted app, so I've left my try-catches). Yeah, if there is one thing I know well it's the Android Status Bar, hence me developing [StatusBar+](https://play.google.com/store/apps/details?id=com.tombarrasso.android.wp7bar)! Just wanted to feel helpful, you guys have done so much on this library there isn't much for me to offer.

@chrisjenx Sorry, yes. It is wrapped in a RelativeLayout (is that perhaps the problem)? It also has an @android:id/empty layout for while it is loading. And the ListView in ContentViewBehind is added to a FrameLayout.

Here is what I did to test. I added log calls to ContentViewBehind and onInterceptTouchEvent is called but NOT onTouchEvent. The log calls in ContentViewAbove are NOT called when touching the ContentViewBehind, which is better than it was last night! For some reason the events still don't get passed through to children. My ListView isn't getting any touch events whatsoever, but I can't figure out why.

**Comment by chrisjenx** [comment] 2012-08-07 22:35
@Tombarr humm yeah unlikely, I use a FrameLayout and dump a fragment in it (barely put anything in the activity these days). So that shouldn't cause it.

You using the latest version of ACL? Don't think thats the issue, but might be a random pager fix, (I haven't checked the diff tbh though).

FYI - @jfeinstein10 has done all the work, i've only committed some minor fixes.

**Comment by Tombarr** [comment] 2012-08-08 01:23
Well then @jfeinstein10 thank you for your great work!

@chrisjenx  So I've gotten to testing the latest version of SlidingMenu (yeah I've got the latest ACL and ABS but I'm not using ViewPagers anywhere). On my Galaxy Nexus touch events work just fine, on my Galaxy S3 nothing goes through. This is VERY odd. I see the log calls only for onInterceptTouchEvent still on my Galaxy Nexus, and yet they pass through ContentViewBehind. I'll see what else I can do to fix it.

**Comment by jfeinstein10** [comment] 2012-08-08 18:09
You're very welcome :D @chrisjenx you've been very helpful with feedback and testing.

onInterceptTouchEvent should get called every time you touch any "element" of the CustomViewAbove, but so long as it returns false, the touch event will not get delivered to any child of the CustomViewAbove. The kind of behavior that you're seeing is expected for the Galaxy Nexus. I would try seeing if onInterceptTouchEvent somehow returns true on the Galaxy S 3. If it does, then that's a pretty bad bug :/. Let me know when you can.

**Comment by kieran-fleming** [comment] 2012-08-30 06:50
The bug with margin swiping on the S3 is caused because that part of the code doesn't scale to the screen density.
In CustomViewAbove, line 975, both the getWidth() call and mSlidingViewThreshold are in pixels so need to be scaled.

**Comment by jfeinstein10** [comment] 2012-08-30 13:01
Haha what a rookie mistake on my part. I'll fix that up today. Thanks so much for finding that

**Comment by BartoszJarocki** [comment] 2012-08-31 08:53
I have a question regarding TOUCHMODE_MARGIN.
When TOUCHMODE_MARGIN is set, and we have UP button it is impossible to click on it, becouse of else if at line 1147 in CustomViewAbove. It is possible, to fix it somehow?

btw, great work, really. :)

**Comment by marcosalis** [comment] 2012-08-31 11:38
Hi, I'm still experiencing the issue with TOUCHMODE_MARGIN on an HTC Sensation after having pulled all your recent commits: is there something else we can try to sort it out?

**Comment by jfeinstein10** [comment] 2012-09-09 00:16
Ping. Has this still been an issue with the newest version?

**Comment by BartoszJarocki** [comment] 2012-09-10 05:46
Galaxy Nexus, Galaxy S, I5800 - everything working great. thanks !

**Comment by jfeinstein10** [comment] 2012-09-11 01:20
Wonderful! Thanks for reporting.
Anybody else seen/not seen this issue lately?

**Comment by Blucreation** [comment] 2012-09-13 20:33
Ive just implemented this and i cannot get MARGIN to work it always goes full screen. 

Im using sherlock actionbar and everything works fine in gingerbread and ics and jb but it still goes full screen.

setSlidingActionBarEnabled(true);
setContentView(R.layout.main);
setBehindContentView(R.layout.content_frame);  
getSlidingMenu().setTouchModeBehind(SlidingMenu.TOUCHMODE_MARGIN);

am i implementing it correctly?

**Comment by Blucreation** [comment] 2012-09-14 08:16
Im confused is margin mode where the menu/pullout goes 2/4 away across or does it refer to where you can swipe/pull the menu/pullout from?

For me the thing pulls out fine but the menu/pullout goes full screen and i want it 3/4 across so the original page still shows slightly

**Comment by jfeinstein10** [comment] 2012-09-14 13:09
"For me the thing pulls out fine but the menu/pullout goes full screen and i want it 3/4 across so the original page still shows slightly"

^ this you can set using `setBehindWidth(...)` of `setBehindOffset(...)`. See the README file for what each is.

**Comment by Blucreation** [comment] 2012-09-14 14:27
Cheers spot on.

**Comment by Blucreation** [comment] 2012-09-14 15:08
Quick one how can i tell if the menu is open? so i can stop my other gestures (back forward in webview) from working?

**Comment by jfeinstein10** [comment] 2012-09-14 15:19
`isBehindShowing()`

**Comment by Blucreation** [comment] 2012-09-14 19:07
Cheers

**Comment by taylorludwig** [comment] 2012-10-03 08:11
On my HTC One X I have this same problem even on the samples app. 

It acts like the margin is very small.  About 1 out of 20 tries I am able to pull the menu out if I am able to touch in just the right spot.  

Thanks for the project, with the fullscreen mode on it works great and is a huge time saver.

**Comment by nixa** [comment] 2012-10-03 10:40
+1 on HTC One X. Margin seems to be very small.

**Comment by nadavfima** [comment] 2012-10-12 04:14
+1 on the HTC One X.

**Comment by jfeinstein10** [comment] 2012-10-12 06:20
Can somebody with an HTC One X please log the value of `pixels` in `CustomViewAbove` at line 668 and report it here? I don't have an HTC One X to test with myself :(

**Comment by taylorludwig** [comment] 2012-10-12 06:37
pixels shows 20.

On Thu, Oct 11, 2012 at 11:21 PM, Jeremy Feinstein <notifications@github.com

**Comment by jfeinstein10** [comment] 2013-01-03 16:46
Fixed via size change to 48dp

**Closed as completed by jfeinstein10** 2013-01-03 16:46 UTC
