### ISSUE TITLE
Simultaneous Left & Right Menu Swipe Gesture Breaks with new Fragments

### ISSUE THREAD

**Issue by mohitsud** [jfeinstein10/SlidingMenu#151] opened 2012-11-26 16:28 UTC
Hi there,
I have explored your LeftAndRightActivity and it is exactly what I need however, I did find a pretty serious bug.

In the LeftAndRightActivity class, I changed the main content to a different Fragment that is not of type ListFragment. Doing this breaks the left and right swipe gestures to bring up the menu.  Do you have any thoughts on why this is occuring?

Here is what I changed:

LeftAndRightActivity.java

//getSupportFragmentManager().beginTransaction().replace(R.id.content_frame, new SampleListFragment()).commit(); <-- removed this line

getSupportFragmentManager().beginTransaction().replace(R.id.content_frame, new SimpleFragment()).commit(); <-- created new SimpleFragment

And SimpleFragment.java (new)  looks like this:

**Comment by jfeinstein10** [comment] 2012-11-26 16:38
Eagerly awaiting the end of this post :)

**Comment by mohitsud** [comment] 2012-11-26 16:43
public class SimpleFragment  extends ListFragment {

```
public SimpleFragment() {
    // TODO Auto-generated constructor stub
}

public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    return inflater.inflate(R.layout.list, null);
}
```

}

**Comment by jfeinstein10** [comment] 2012-11-26 16:50
Did you close this on purpose?

**Comment by mohitsud** [comment] 2012-11-26 16:52
Sorry, no . This is still a very active and easily replicatable issue. I am just new to git hub.

**Comment by mohitsud** [comment] 2012-11-26 20:20
Were you Able to replicate the issue Jeff?

**Comment by jfeinstein10** [comment] 2012-11-26 20:56
I will not be able to try it out until later tonight. I'm working now. (Also, my name is Jeremy :smile: )

**Comment by mohitsud** [comment] 2012-11-26 20:59
ok..Sorry about not getting your name right. I appreciate all of your hard work and the time you spend maintaining this public git.

**Comment by jfeinstein10** [comment] 2012-11-26 22:06
No need to apologize :)
And you're very welcome!

**Comment by mohitsud** [comment] 2012-11-27 14:16
Hi Jeremy,

I was just wondering if you had any luck reproducing it, or any time to attempt to reproduce it. Tanks.

**Comment by jfeinstein10** [comment] 2012-11-27 15:55
I spoke too quickly. Definitely getting issues :\

**Comment by mohitsud** [comment] 2012-11-27 16:16
Hahahaha, I am glad its not just me having the problem. 

By the way, your latest updates this morning fixed the left menu being visible for a split second when you open the right menu.

**Comment by mohitsud** [comment] 2012-11-27 16:16
Sorry for the closing / reopening. They shouldn't put the close button right next to the comment button on GIT.

**Comment by lowleetak** [comment] 2012-11-28 02:23
I am having his problem too by simply changing SampleListFragment to ColorFragment in LeftAndRightActivity.
After some debugging, found out the cause might be due to there is no child to handle touchEvent in ColorFragment (It only contain a RelativeLayout). When there is no child to handle the touchEvent, it will fire back to ViewGroup onTouchEvent which make subsequent onInterceptTouchEvnt not fire. In SampleListFragment, it contain a list of child that will consume the touchEvent, so it have no problem.

If we add a button into ColorFragment, you can notice that you can drag out the menu by slide on top of the button, but not other place. Slide on ActionBar will work too.

I will continue looking on the touch event handling in CustomViewAbove.

**Comment by lowleetak** [comment] 2012-11-28 02:56
Seems like when there is no child in the ViewGroup, the touch event not working properly.
Workaround on this, add the following CustomLinearLayout as child in ColorFragment.

```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    if (savedInstanceState != null)
        mColorRes = savedInstanceState.getInt("mColorRes");
    int color = getResources().getColor(mColorRes);
    // construct the RelativeLayout
    RelativeLayout v = new RelativeLayout(getActivity());
    v.setBackgroundColor(color);
    v.addView(new CustomLinearLayout(getActivity()), new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT));
    return v;
}

class CustomLinearLayout extends LinearLayout
{
    public CustomLinearLayout(Context context) {
        super(context);
    }

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        return true;
    }
}
```

**Comment by jfeinstein10** [comment] 2013-01-15 19:01
I'm pretty sure this has been fixed, so I'm closing it. Let me know.

**Closed as completed by jfeinstein10** 2013-01-15 19:01 UTC
